language: node_js
node_js:
- node

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_1b0d935eda41_key -iv $encrypted_1b0d935eda41_iv -in travis_key.enc -out travis_key -d
- eval "$(ssh-agent -s)"
- chmod 600 travis_key
- ssh-add travis_key

install:
- npm install

script:
- npm run test -- --browsers ChromeHeadlessNoSandbox --watch=false
- npm run build -- --output-path=./dist/out --prod

after_success:
- docker login -u $REGISTRY_USER -p $REGISTRY_PASS
- docker build -t $REGISTRY_REPO .
- docker push $REGISTRY_REPO
- ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST "(docker stop $CONTAINER_NAME || true) && (docker rm $CONTAINER_NAME || true)"
- ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST docker pull $REGISTRY_REPO
- ssh -o "StrictHostKeyChecking no" $HOST_USER@$HOST docker run -d -p 80:80 --name $CONTAINER_NAME -v "/home/user/playlytics/nginx":"/etc/nginx/conf.d" $REGISTRY_REPO
